<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;
use App\Helpers\Helper;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['code' => '+93', 'flag' => 'AF', 'name' => 'Afghanistan', 'languages' => 'Dari, Pashto', 'language_code' => 'ps, fa', 'country_code' => '93', 'country_iso_code_3' => 'AFG', 'country_iso_code_2' => 'AF', 'currency_name' => 'Afghani', 'currency_symbol' => '؋'],
            ['code' => '+355', 'flag' => 'AL', 'name' => 'Albania', 'languages' => 'Albanian', 'language_code' => 'sq', 'country_code' => '355', 'country_iso_code_3' => 'ALB', 'country_iso_code_2' => 'AL', 'currency_name' => 'Albanian lek', 'currency_symbol' => 'L'],
            ['code' => '+213', 'flag' => 'DZ', 'name' => 'Algeria', 'languages' => 'Arabic, Berber', 'language_code' => 'ar, ber', 'country_code' => '213', 'country_iso_code_3' => 'DZA', 'country_iso_code_2' => 'DZ', 'currency_name' => 'Algerian dinar', 'currency_symbol' => 'د.ج'],
            ['code' => '+376', 'flag' => 'AD', 'name' => 'Andorra', 'languages' => 'Catalan', 'language_code' => 'ca', 'country_code' => '376', 'country_iso_code_3' => 'AND', 'country_iso_code_2' => 'AD', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+244', 'flag' => 'AO', 'name' => 'Angola', 'languages' => 'Portuguese', 'language_code' => 'pt', 'country_code' => '244', 'country_iso_code_3' => 'AGO', 'country_iso_code_2' => 'AO', 'currency_name' => 'Kwanza', 'currency_symbol' => 'Kz'],
            ['code' => '+1-268', 'flag' => 'AG', 'name' => 'Antigua and Barbuda', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'ATG', 'country_iso_code_2' => 'AG', 'currency_name' => 'East Caribbean dollar', 'currency_symbol' => '$'],
            ['code' => '+54', 'flag' => 'AR', 'name' => 'Argentina', 'languages' => 'Spanish', 'language_code' => 'es', 'country_code' => '54', 'country_iso_code_3' => 'ARG', 'country_iso_code_2' => 'AR', 'currency_name' => 'Argentine peso', 'currency_symbol' => '$'],
            ['code' => '+61', 'flag' => 'AU', 'name' => 'Australia', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '61', 'country_iso_code_3' => 'AUS', 'country_iso_code_2' => 'AU', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['code' => '+43', 'flag' => 'AT', 'name' => 'Austria', 'languages' => 'German', 'language_code' => 'de', 'country_code' => '43', 'country_iso_code_3' => 'AUT', 'country_iso_code_2' => 'AT', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+994', 'flag' => 'AZ', 'name' => 'Azerbaijan', 'languages' => 'Azerbaijani', 'language_code' => 'az', 'country_code' => '994', 'country_iso_code_3' => 'AZE', 'country_iso_code_2' => 'AZ', 'currency_name' => 'Azerbaijani manat', 'currency_symbol' => '₼'],
            ['code' => '+1-242', 'flag' => 'BS', 'name' => 'Bahamas', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'BHS', 'country_iso_code_2' => 'BS', 'currency_name' => 'Bahamian dollar', 'currency_symbol' => '$'],
            ['code' => '+973', 'flag' => 'BH', 'name' => 'Bahrain', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '973', 'country_iso_code_3' => 'BHR', 'country_iso_code_2' => 'BH', 'currency_name' => 'Bahraini dinar', 'currency_symbol' => '.د.ب'],
            ['code' => '+880', 'flag' => 'BD', 'name' => 'Bangladesh', 'languages' => 'Bengali', 'language_code' => 'bn', 'country_code' => '880', 'country_iso_code_3' => 'BGD', 'country_iso_code_2' => 'BD', 'currency_name' => 'Bangladeshi taka', 'currency_symbol' => '৳'],
            ['code' => '+1-246', 'flag' => 'BB', 'name' => 'Barbados', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'BRB', 'country_iso_code_2' => 'BB', 'currency_name' => 'Barbadian dollar', 'currency_symbol' => '$'],
            ['code' => '+375', 'flag' => 'BY', 'name' => 'Belarus', 'languages' => 'Belarusian, Russian', 'language_code' => 'be, ru', 'country_code' => '375', 'country_iso_code_3' => 'BLR', 'country_iso_code_2' => 'BY', 'currency_name' => 'Belarusian ruble', 'currency_symbol' => 'Br'],
            ['code' => '+32', 'flag' => 'BE', 'name' => 'Belgium', 'languages' => 'Dutch, French, German', 'language_code' => 'nl, fr, de', 'country_code' => '32', 'country_iso_code_3' => 'BEL', 'country_iso_code_2' => 'BE', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+501', 'flag' => 'BZ', 'name' => 'Belize', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '501', 'country_iso_code_3' => 'BLZ', 'country_iso_code_2' => 'BZ', 'currency_name' => 'Belize dollar', 'currency_symbol' => '$'],
            ['code' => '+229', 'flag' => 'BJ', 'name' => 'Benin', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '229', 'country_iso_code_3' => 'BEN', 'country_iso_code_2' => 'BJ', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'Fr'],
            ['code' => '+1-441', 'flag' => 'BM', 'name' => 'Bermuda', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'BMU', 'country_iso_code_2' => 'BM', 'currency_name' => 'Bermudian dollar', 'currency_symbol' => '$'],
            ['code' => '+975', 'flag' => 'BT', 'name' => 'Bhutan', 'languages' => 'Dzongkha', 'language_code' => 'dz', 'country_code' => '975', 'country_iso_code_3' => 'BTN', 'country_iso_code_2' => 'BT', 'currency_name' => 'Bhutanese ngultrum', 'currency_symbol' => 'Nu'],
            ['code' => '+591', 'flag' => 'BO', 'name' => 'Bolivia', 'languages' => 'Spanish, Quechua, Aymara, Guarani', 'language_code' => 'es, qu, ay, gn', 'country_code' => '591', 'country_iso_code_3' => 'BOL', 'country_iso_code_2' => 'BO', 'currency_name' => 'Bolivian boliviano', 'currency_symbol' => 'Bs'],
            ['code' => '+387', 'flag' => 'BA', 'name' => 'Bosnia and Herzegovina', 'languages' => 'Bosnian, Croatian, Serbian', 'language_code' => 'bs, hr, sr', 'country_code' => '387', 'country_iso_code_3' => 'BIH', 'country_iso_code_2' => 'BA', 'currency_name' => 'Bosnia and Herzegovina convertible mark', 'currency_symbol' => 'KM'],
            ['code' => '+1-473', 'flag' => 'GD', 'name' => 'Grenada', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'GRD', 'country_iso_code_2' => 'GD', 'currency_name' => 'East Caribbean dollar', 'currency_symbol' => '$'],
            ['code' => '+502', 'flag' => 'GT', 'name' => 'Guatemala', 'languages' => 'Spanish', 'language_code' => 'es', 'country_code' => '502', 'country_iso_code_3' => 'GTM', 'country_iso_code_2' => 'GT', 'currency_name' => 'Guatemalan quetzal', 'currency_symbol' => 'Q'],
            ['code' => '+504', 'flag' => 'HN', 'name' => 'Honduras', 'languages' => 'Spanish', 'language_code' => 'es', 'country_code' => '504', 'country_iso_code_3' => 'HND', 'country_iso_code_2' => 'HN', 'currency_name' => 'Honduran lempira', 'currency_symbol' => 'L'],
            ['code' => '+852', 'flag' => 'HK', 'name' => 'Hong Kong', 'languages' => 'Chinese, English', 'language_code' => 'zh, en', 'country_code' => '852', 'country_iso_code_3' => 'HKG', 'country_iso_code_2' => 'HK', 'currency_name' => 'Hong Kong dollar', 'currency_symbol' => '$'],
            ['code' => '+36', 'flag' => 'HU', 'name' => 'Hungary', 'languages' => 'Hungarian', 'language_code' => 'hu', 'country_code' => '36', 'country_iso_code_3' => 'HUN', 'country_iso_code_2' => 'HU', 'currency_name' => 'Hungarian forint', 'currency_symbol' => 'Ft'],
            ['code' => '+354', 'flag' => 'IS', 'name' => 'Iceland', 'languages' => 'Icelandic', 'language_code' => 'is', 'country_code' => '354', 'country_iso_code_3' => 'ISL', 'country_iso_code_2' => 'IS', 'currency_name' => 'Icelandic króna', 'currency_symbol' => 'kr'],
            ['code' => '+91', 'flag' => 'IN', 'name' => 'India', 'languages' => 'Hindi, English', 'language_code' => 'hi, en', 'country_code' => '91', 'country_iso_code_3' => 'IND', 'country_iso_code_2' => 'IN', 'currency_name' => 'Indian rupee', 'currency_symbol' => '₹'],
            ['code' => '+92', 'flag' => 'PK', 'name' => 'Pakistan', 'languages' => 'Urdu, English', 'language_code' => 'ur, en', 'country_code' => '92', 'country_iso_code_3' => 'PAK', 'country_iso_code_2' => 'PK', 'currency_name' => 'Pakistani Rupee', 'currency_symbol' => '₨'],
            ['code' => '+62', 'flag' => 'ID', 'name' => 'Indonesia', 'languages' => 'Indonesian', 'language_code' => 'id', 'country_code' => '62', 'country_iso_code_3' => 'IDN', 'country_iso_code_2' => 'ID', 'currency_name' => 'Indonesian rupiah', 'currency_symbol' => 'Rp'],
            ['code' => '+964', 'flag' => 'IQ', 'name' => 'Iraq', 'languages' => 'Arabic, Kurdish', 'language_code' => 'ar, ku', 'country_code' => '964', 'country_iso_code_3' => 'IRQ', 'country_iso_code_2' => 'IQ', 'currency_name' => 'Iraqi dinar', 'currency_symbol' => 'ع.د'],
            ['code' => '+353', 'flag' => 'IE', 'name' => 'Ireland', 'languages' => 'Irish, English', 'language_code' => 'ga, en', 'country_code' => '353', 'country_iso_code_3' => 'IRL', 'country_iso_code_2' => 'IE', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+972', 'flag' => 'IL', 'name' => 'Israel', 'languages' => 'Hebrew, Arabic', 'language_code' => 'he, ar', 'country_code' => '972', 'country_iso_code_3' => 'ISR', 'country_iso_code_2' => 'IL', 'currency_name' => 'Israeli new shekel', 'currency_symbol' => '₪'],
            ['code' => '+39', 'flag' => 'IT', 'name' => 'Italy', 'languages' => 'Italian', 'language_code' => 'it', 'country_code' => '39', 'country_iso_code_3' => 'ITA', 'country_iso_code_2' => 'IT', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+1-876', 'flag' => 'JM', 'name' => 'Jamaica', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'JAM', 'country_iso_code_2' => 'JM', 'currency_name' => 'Jamaican dollar', 'currency_symbol' => '$'],
            ['code' => '+81', 'flag' => 'JP', 'name' => 'Japan', 'languages' => 'Japanese', 'language_code' => 'ja', 'country_code' => '81', 'country_iso_code_3' => 'JPN', 'country_iso_code_2' => 'JP', 'currency_name' => 'Yen', 'currency_symbol' => '¥'],
            ['code' => '+962', 'flag' => 'JO', 'name' => 'Jordan', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '962', 'country_iso_code_3' => 'JOR', 'country_iso_code_2' => 'JO', 'currency_name' => 'Jordanian dinar', 'currency_symbol' => 'د.أ'],
            ['code' => '+7', 'flag' => 'KZ', 'name' => 'Kazakhstan', 'languages' => 'Kazakh, Russian', 'language_code' => 'kk, ru', 'country_code' => '7', 'country_iso_code_3' => 'KAZ', 'country_iso_code_2' => 'KZ', 'currency_name' => 'Kazakhstani tenge', 'currency_symbol' => '₸'],
            ['code' => '+254', 'flag' => 'KE', 'name' => 'Kenya', 'languages' => 'Swahili, English', 'language_code' => 'sw, en', 'country_code' => '254', 'country_iso_code_3' => 'KEN', 'country_iso_code_2' => 'KE', 'currency_name' => 'Kenyan shilling', 'currency_symbol' => 'KSh'],
            ['code' => '+686', 'flag' => 'KI', 'name' => 'Kiribati', 'languages' => 'English, Gilbertese', 'language_code' => 'en, gil', 'country_code' => '686', 'country_iso_code_3' => 'KIR', 'country_iso_code_2' => 'KI', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['code' => '+965', 'flag' => 'KW', 'name' => 'Kuwait', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '965', 'country_iso_code_3' => 'KWT', 'country_iso_code_2' => 'KW', 'currency_name' => 'Kuwaiti dinar', 'currency_symbol' => 'د.ك'],
            ['code' => '+996', 'flag' => 'KG', 'name' => 'Kyrgyzstan', 'languages' => 'Kyrgyz, Russian', 'language_code' => 'ky, ru', 'country_code' => '996', 'country_iso_code_3' => 'KGZ', 'country_iso_code_2' => 'KG', 'currency_name' => 'Kyrgyzstani som', 'currency_symbol' => 'с'],
            ['code' => '+856', 'flag' => 'LA', 'name' => 'Laos', 'languages' => 'Lao', 'language_code' => 'lo', 'country_code' => '856', 'country_iso_code_3' => 'LAO', 'country_iso_code_2' => 'LA', 'currency_name' => 'Lao kip', 'currency_symbol' => '₭'],
            ['code' => '+371', 'flag' => 'LV', 'name' => 'Latvia', 'languages' => 'Latvian', 'language_code' => 'lv', 'country_code' => '371', 'country_iso_code_3' => 'LVA', 'country_iso_code_2' => 'LV', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+961', 'flag' => 'LB', 'name' => 'Lebanon', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '961', 'country_iso_code_3' => 'LBN', 'country_iso_code_2' => 'LB', 'currency_name' => 'Lebanese pound', 'currency_symbol' => 'ل.ل'],
            ['code' => '+266', 'flag' => 'LS', 'name' => 'Lesotho', 'languages' => 'Sesotho, English', 'language_code' => 'st, en', 'country_code' => '266', 'country_iso_code_3' => 'LSO', 'country_iso_code_2' => 'LS', 'currency_name' => 'Lesotho loti', 'currency_symbol' => 'L'],
            ['code' => '+231', 'flag' => 'LR', 'name' => 'Liberia', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '231', 'country_iso_code_3' => 'LBR', 'country_iso_code_2' => 'LR', 'currency_name' => 'Liberian dollar', 'currency_symbol' => '$'],
            ['code' => '+218', 'flag' => 'LY', 'name' => 'Libya', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '218', 'country_iso_code_3' => 'LBY', 'country_iso_code_2' => 'LY', 'currency_name' => 'Libyan dinar', 'currency_symbol' => 'د.ل'],
            ['code' => '+423', 'flag' => 'LI', 'name' => 'Liechtenstein', 'languages' => 'German', 'language_code' => 'de', 'country_code' => '423', 'country_iso_code_3' => 'LIE', 'country_iso_code_2' => 'LI', 'currency_name' => 'Swiss franc', 'currency_symbol' => 'CHF'],
            ['code' => '+370', 'flag' => 'LT', 'name' => 'Lithuania', 'languages' => 'Lithuanian', 'language_code' => 'lt', 'country_code' => '370', 'country_iso_code_3' => 'LTU', 'country_iso_code_2' => 'LT', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+352', 'flag' => 'LU', 'name' => 'Luxembourg', 'languages' => 'Luxembourgish, French, German', 'language_code' => 'lb, fr, de', 'country_code' => '352', 'country_iso_code_3' => 'LUX', 'country_iso_code_2' => 'LU', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+853', 'flag' => 'MO', 'name' => 'Macau', 'languages' => 'Chinese, Portuguese', 'language_code' => 'zh, pt', 'country_code' => '853', 'country_iso_code_3' => 'MAC', 'country_iso_code_2' => 'MO', 'currency_name' => 'Macanese pataca', 'currency_symbol' => 'MOP$'],
            ['code' => '+853', 'flag' => 'MO', 'name' => 'Macau', 'languages' => 'Chinese, Portuguese', 'language_code' => 'zh, pt', 'country_code' => '853', 'country_iso_code_3' => 'MAC', 'country_iso_code_2' => 'MO', 'currency_name' => 'Macanese pataca', 'currency_symbol' => 'MOP$'],
            ['code' => '+262', 'flag' => 'YT', 'name' => 'Mayotte', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '262', 'country_iso_code_3' => 'MYT', 'country_iso_code_2' => 'YT', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+60', 'flag' => 'MY', 'name' => 'Malaysia', 'languages' => 'Malay', 'language_code' => 'ms', 'country_code' => '60', 'country_iso_code_3' => 'MYS', 'country_iso_code_2' => 'MY', 'currency_name' => 'Ringgit', 'currency_symbol' => 'RM'],
            ['code' => '+960', 'flag' => 'MV', 'name' => 'Maldives', 'languages' => 'Maldivian', 'language_code' => 'dv', 'country_code' => '960', 'country_iso_code_3' => 'MDV', 'country_iso_code_2' => 'MV', 'currency_name' => 'Maldivian rufiyaa', 'currency_symbol' => 'Rf'],
            ['code' => '+223', 'flag' => 'ML', 'name' => 'Mali', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '223', 'country_iso_code_3' => 'MLI', 'country_iso_code_2' => 'ML', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['code' => '+356', 'flag' => 'MT', 'name' => 'Malta', 'languages' => 'Maltese, English', 'language_code' => 'mt, en', 'country_code' => '356', 'country_iso_code_3' => 'MLT', 'country_iso_code_2' => 'MT', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+1-246', 'flag' => 'BB', 'name' => 'Barbados', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'BRB', 'country_iso_code_2' => 'BB', 'currency_name' => 'Barbadian dollar', 'currency_symbol' => '$'],
            ['code' => '+590', 'flag' => 'GP', 'name' => 'Guadeloupe', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '590', 'country_iso_code_3' => 'GLP', 'country_iso_code_2' => 'GP', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+1-345', 'flag' => 'KY', 'name' => 'Cayman Islands', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'CYM', 'country_iso_code_2' => 'KY', 'currency_name' => 'Cayman Islands dollar', 'currency_symbol' => '$'],
            ['code' => '+20', 'flag' => 'EG', 'name' => 'Egypt', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '20', 'country_iso_code_3' => 'EGY', 'country_iso_code_2' => 'EG', 'currency_name' => 'Egyptian pound', 'currency_symbol' => 'E£'],
            ['code' => '+503', 'flag' => 'SV', 'name' => 'El Salvador', 'languages' => 'Spanish', 'language_code' => 'es', 'country_code' => '503', 'country_iso_code_3' => 'SLV', 'country_iso_code_2' => 'SV', 'currency_name' => 'US Dollar', 'currency_symbol' => '$'],
            ['code' => '+240', 'flag' => 'GQ', 'name' => 'Equatorial Guinea', 'languages' => 'Spanish, French, Portuguese', 'language_code' => 'es, fr, pt', 'country_code' => '240', 'country_iso_code_3' => 'GNQ', 'country_iso_code_2' => 'GQ', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'CFA'],
            ['code' => '+291', 'flag' => 'ER', 'name' => 'Eritrea', 'languages' => 'Tigrinya, Arabic, English', 'language_code' => 'ti, ar, en', 'country_code' => '291', 'country_iso_code_3' => 'ERI', 'country_iso_code_2' => 'ER', 'currency_name' => 'Eritrean nakfa', 'currency_symbol' => 'Nfk'],
            ['code' => '+372', 'flag' => 'EE', 'name' => 'Estonia', 'languages' => 'Estonian', 'language_code' => 'et', 'country_code' => '372', 'country_iso_code_3' => 'EST', 'country_iso_code_2' => 'EE', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+251', 'flag' => 'ET', 'name' => 'Ethiopia', 'languages' => 'Amharic', 'language_code' => 'am', 'country_code' => '251', 'country_iso_code_3' => 'ETH', 'country_iso_code_2' => 'ET', 'currency_name' => 'Ethiopian birr', 'currency_symbol' => 'Br'],
            ['code' => '+500', 'flag' => 'FK', 'name' => 'Falkland Islands', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '500', 'country_iso_code_3' => 'FLK', 'country_iso_code_2' => 'FK', 'currency_name' => 'Falkland Islands pound', 'currency_symbol' => '£'],
            ['code' => '+298', 'flag' => 'FO', 'name' => 'Faroe Islands', 'languages' => 'Faroese, Danish', 'language_code' => 'fo, da', 'country_code' => '298', 'country_iso_code_3' => 'FRO', 'country_iso_code_2' => 'FO', 'currency_name' => 'Danish krone', 'currency_symbol' => 'kr'],
            ['code' => '+679', 'flag' => 'FJ', 'name' => 'Fiji', 'languages' => 'English, Fijian, Hindi', 'language_code' => 'en, fj, hi', 'country_code' => '679', 'country_iso_code_3' => 'FJI', 'country_iso_code_2' => 'FJ', 'currency_name' => 'Fijian dollar', 'currency_symbol' => '$'],
            ['code' => '+358', 'flag' => 'FI', 'name' => 'Finland', 'languages' => 'Finnish, Swedish', 'language_code' => 'fi, sv', 'country_code' => '358', 'country_iso_code_3' => 'FIN', 'country_iso_code_2' => 'FI', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+33', 'flag' => 'FR', 'name' => 'France', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '33', 'country_iso_code_3' => 'FRA', 'country_iso_code_2' => 'FR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+241', 'flag' => 'GA', 'name' => 'Gabon', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '241', 'country_iso_code_3' => 'GAB', 'country_iso_code_2' => 'GA', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'CFA'],
            ['code' => '+220', 'flag' => 'GM', 'name' => 'Gambia', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '220', 'country_iso_code_3' => 'GMB', 'country_iso_code_2' => 'GM', 'currency_name' => 'Gambian dalasi', 'currency_symbol' => 'D'],
            ['code' => '+995', 'flag' => 'GE', 'name' => 'Georgia', 'languages' => 'Georgian', 'language_code' => 'ka', 'country_code' => '995', 'country_iso_code_3' => 'GEO', 'country_iso_code_2' => 'GE', 'currency_name' => 'Lari', 'currency_symbol' => '₾'],
            ['code' => '+49', 'flag' => 'DE', 'name' => 'Germany', 'languages' => 'German', 'language_code' => 'de', 'country_code' => '49', 'country_iso_code_3' => 'DEU', 'country_iso_code_2' => 'DE', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+233', 'flag' => 'GH', 'name' => 'Ghana', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '233', 'country_iso_code_3' => 'GHA', 'country_iso_code_2' => 'GH', 'currency_name' => 'Ghanaian cedi', 'currency_symbol' => '₵'],
            ['code' => '+350', 'flag' => 'GI', 'name' => 'Gibraltar', 'languages' => 'English, Spanish', 'language_code' => 'en, es', 'country_code' => '350', 'country_iso_code_3' => 'GIB', 'country_iso_code_2' => 'GI', 'currency_name' => 'Gibraltar pound', 'currency_symbol' => '£'],
            ['code' => '+30', 'flag' => 'GR', 'name' => 'Greece', 'languages' => 'Greek', 'language_code' => 'el', 'country_code' => '30', 'country_iso_code_3' => 'GRC', 'country_iso_code_2' => 'GR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+30', 'flag' => 'GR', 'name' => 'Greece', 'languages' => 'Greek', 'language_code' => 'el', 'country_code' => '30', 'country_iso_code_3' => 'GRC', 'country_iso_code_2' => 'GR', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+299', 'flag' => 'GL', 'name' => 'Greenland', 'languages' => 'Greenlandic, Danish, English', 'language_code' => 'kl, da, en', 'country_code' => '299', 'country_iso_code_3' => 'GRL', 'country_iso_code_2' => 'GL', 'currency_name' => 'Danish krone', 'currency_symbol' => 'kr'],
            ['code' => '+1473', 'flag' => 'GD', 'name' => 'Grenada', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'GRD', 'country_iso_code_2' => 'GD', 'currency_name' => 'East Caribbean dollar', 'currency_symbol' => '$'],
            ['code' => '+502', 'flag' => 'GT', 'name' => 'Guatemala', 'languages' => 'Spanish', 'language_code' => 'es', 'country_code' => '502', 'country_iso_code_3' => 'GTM', 'country_iso_code_2' => 'GT', 'currency_name' => 'Quetzal', 'currency_symbol' => 'Q'],
            ['code' => '+44', 'flag' => 'GG', 'name' => 'Guernsey', 'languages' => 'English, French', 'language_code' => 'en, fr', 'country_code' => '44', 'country_iso_code_3' => 'GGY', 'country_iso_code_2' => 'GG', 'currency_name' => 'Pound sterling', 'currency_symbol' => '£'],
            ['code' => '+224', 'flag' => 'GN', 'name' => 'Guinea', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '224', 'country_iso_code_3' => 'GIN', 'country_iso_code_2' => 'GN', 'currency_name' => 'Guinean franc', 'currency_symbol' => 'FG'],
            ['code' => '+245', 'flag' => 'GW', 'name' => 'Guinea-Bissau', 'languages' => 'Portuguese', 'language_code' => 'pt', 'country_code' => '245', 'country_iso_code_3' => 'GNB', 'country_iso_code_2' => 'GW', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['code' => '+595', 'flag' => 'PY', 'name' => 'Paraguay', 'languages' => 'Spanish, Guaraní', 'language_code' => 'es, gn', 'country_code' => '595', 'country_iso_code_3' => 'PRY', 'country_iso_code_2' => 'PY', 'currency_name' => 'Guarani', 'currency_symbol' => '₲'],
            ['code' => '+51', 'flag' => 'PE', 'name' => 'Peru', 'languages' => 'Spanish', 'language_code' => 'es', 'country_code' => '51', 'country_iso_code_3' => 'PER', 'country_iso_code_2' => 'PE', 'currency_name' => 'Sol', 'currency_symbol' => 'S/'],
            ['code' => '+63', 'flag' => 'PH', 'name' => 'Philippines', 'languages' => 'Filipino, English', 'language_code' => 'tl, en', 'country_code' => '63', 'country_iso_code_3' => 'PHL', 'country_iso_code_2' => 'PH', 'currency_name' => 'Philippine peso', 'currency_symbol' => '₱'],
            ['code' => '+48', 'flag' => 'PL', 'name' => 'Poland', 'languages' => 'Polish', 'language_code' => 'pl', 'country_code' => '48', 'country_iso_code_3' => 'POL', 'country_iso_code_2' => 'PL', 'currency_name' => 'Zloty', 'currency_symbol' => 'zł'],
            ['code' => '+351', 'flag' => 'PT', 'name' => 'Portugal', 'languages' => 'Portuguese', 'language_code' => 'pt', 'country_code' => '351', 'country_iso_code_3' => 'PRT', 'country_iso_code_2' => 'PT', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+1-787', 'flag' => 'PR', 'name' => 'Puerto Rico', 'languages' => 'Spanish, English', 'language_code' => 'es, en', 'country_code' => '1', 'country_iso_code_3' => 'PRI', 'country_iso_code_2' => 'PR', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['code' => '+974', 'flag' => 'QA', 'name' => 'Qatar', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '974', 'country_iso_code_3' => 'QAT', 'country_iso_code_2' => 'QA', 'currency_name' => 'Qatari riyal', 'currency_symbol' => 'QR'],
            ['code' => '+262', 'flag' => 'RE', 'name' => 'Réunion', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '262', 'country_iso_code_3' => 'REU', 'country_iso_code_2' => 'RE', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+40', 'flag' => 'RO', 'name' => 'Romania', 'languages' => 'Romanian', 'language_code' => 'ro', 'country_code' => '40', 'country_iso_code_3' => 'ROU', 'country_iso_code_2' => 'RO', 'currency_name' => 'Romanian leu', 'currency_symbol' => 'lei'],
            ['code' => '+7', 'flag' => 'RU', 'name' => 'Russia', 'languages' => 'Russian', 'language_code' => 'ru', 'country_code' => '7', 'country_iso_code_3' => 'RUS', 'country_iso_code_2' => 'RU', 'currency_name' => 'Russian ruble', 'currency_symbol' => '₽'],
            ['code' => '+250', 'flag' => 'RW', 'name' => 'Rwanda', 'languages' => 'Kinyarwanda, French, English', 'language_code' => 'rw, fr, en', 'country_code' => '250', 'country_iso_code_3' => 'RWA', 'country_iso_code_2' => 'RW', 'currency_name' => 'Rwandan franc', 'currency_symbol' => 'Fr'],
            ['code' => '+290', 'flag' => 'SH', 'name' => 'Saint Helena', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '290', 'country_iso_code_3' => 'SHN', 'country_iso_code_2' => 'SH', 'currency_name' => 'Saint Helena pound', 'currency_symbol' => '£'],
            ['code' => '+1-869', 'flag' => 'KN', 'name' => 'Saint Kitts and Nevis', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'KNA', 'country_iso_code_2' => 'KN', 'currency_name' => 'East Caribbean dollar', 'currency_symbol' => '$'],
            ['code' => '+1-758', 'flag' => 'LC', 'name' => 'Saint Lucia', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'LCA', 'country_iso_code_2' => 'LC', 'currency_name' => 'East Caribbean dollar', 'currency_symbol' => '$'],
            ['code' => '+1-784', 'flag' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'VCT', 'country_iso_code_2' => 'VC', 'currency_name' => 'East Caribbean dollar', 'currency_symbol' => '$'],
            ['code' => '+684', 'flag' => 'WS', 'name' => 'Samoa', 'languages' => 'Samoan, English', 'language_code' => 'sm, en', 'country_code' => '684', 'country_iso_code_3' => 'WSM', 'country_iso_code_2' => 'WS', 'currency_name' => 'Tala', 'currency_symbol' => 'WS$'],
            ['code' => '+378', 'flag' => 'SM', 'name' => 'San Marino', 'languages' => 'Italian', 'language_code' => 'it', 'country_code' => '378', 'country_iso_code_3' => 'SMR', 'country_iso_code_2' => 'SM', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+239', 'flag' => 'ST', 'name' => 'São Tomé and Príncipe', 'languages' => 'Portuguese', 'language_code' => 'pt', 'country_code' => '239', 'country_iso_code_3' => 'STP', 'country_iso_code_2' => 'ST', 'currency_name' => 'Dobra', 'currency_symbol' => 'Db'],
            ['code' => '+966', 'flag' => 'SA', 'name' => 'Saudi Arabia', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '966', 'country_iso_code_3' => 'SAU', 'country_iso_code_2' => 'SA', 'currency_name' => 'Saudi riyal', 'currency_symbol' => 'ر.س'],
            ['code' => '+221', 'flag' => 'SN', 'name' => 'Senegal', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '221', 'country_iso_code_3' => 'SEN', 'country_iso_code_2' => 'SN', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['code' => '+381', 'flag' => 'RS', 'name' => 'Serbia', 'languages' => 'Serbian', 'language_code' => 'sr', 'country_code' => '381', 'country_iso_code_3' => 'SRB', 'country_iso_code_2' => 'RS', 'currency_name' => 'Serbian dinar', 'currency_symbol' => 'дин'],
            ['code' => '+248', 'flag' => 'SC', 'name' => 'Seychelles', 'languages' => 'Seychellois Creole, English, French', 'language_code' => 'cr, en, fr', 'country_code' => '248', 'country_iso_code_3' => 'SYC', 'country_iso_code_2' => 'SC', 'currency_name' => 'Seychellois rupee', 'currency_symbol' => '₨'],
            ['code' => '+232', 'flag' => 'SL', 'name' => 'Sierra Leone', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '232', 'country_iso_code_3' => 'SLE', 'country_iso_code_2' => 'SL', 'currency_name' => 'Leone', 'currency_symbol' => 'Le'],
            ['code' => '+65', 'flag' => 'SG', 'name' => 'Singapore', 'languages' => 'English, Malay, Tamil, Mandarin', 'language_code' => 'en, ms, ta, zh', 'country_code' => '65', 'country_iso_code_3' => 'SGP', 'country_iso_code_2' => 'SG', 'currency_name' => 'Singapore dollar', 'currency_symbol' => 'S$'],
            ['code' => '+421', 'flag' => 'SK', 'name' => 'Slovakia', 'languages' => 'Slovak', 'language_code' => 'sk', 'country_code' => '421', 'country_iso_code_3' => 'SVK', 'country_iso_code_2' => 'SK', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+386', 'flag' => 'SI', 'name' => 'Slovenia', 'languages' => 'Slovene', 'language_code' => 'sl', 'country_code' => '386', 'country_iso_code_3' => 'SVN', 'country_iso_code_2' => 'SI', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+677', 'flag' => 'SB', 'name' => 'Solomon Islands', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '677', 'country_iso_code_3' => 'SLB', 'country_iso_code_2' => 'SB', 'currency_name' => 'Solomon Islands dollar', 'currency_symbol' => 'SI$'],
            ['code' => '+677', 'flag' => 'SB', 'name' => 'Solomon Islands', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '677', 'country_iso_code_3' => 'SLB', 'country_iso_code_2' => 'SB', 'currency_name' => 'Solomon Islands dollar', 'currency_symbol' => 'SI$'],
            ['code' => '+27', 'flag' => 'ZA', 'name' => 'South Africa', 'languages' => 'Afrikaans, English, Zulu, Xhosa', 'language_code' => 'af, en, zu, xh', 'country_code' => '27', 'country_iso_code_3' => 'ZAF', 'country_iso_code_2' => 'ZA', 'currency_name' => 'South African rand', 'currency_symbol' => 'R'],
            ['code' => '+211', 'flag' => 'SS', 'name' => 'South Sudan', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '211', 'country_iso_code_3' => 'SSD', 'country_iso_code_2' => 'SS', 'currency_name' => 'South Sudanese pound', 'currency_symbol' => '£'],
            ['code' => '+34', 'flag' => 'ES', 'name' => 'Spain', 'languages' => 'Spanish', 'language_code' => 'es', 'country_code' => '34', 'country_iso_code_3' => 'ESP', 'country_iso_code_2' => 'ES', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+94', 'flag' => 'LK', 'name' => 'Sri Lanka', 'languages' => 'Sinhalese, Tamil', 'language_code' => 'si, ta', 'country_code' => '94', 'country_iso_code_3' => 'LKA', 'country_iso_code_2' => 'LK', 'currency_name' => 'Sri Lankan rupee', 'currency_symbol' => 'Rs'],
            ['code' => '+249', 'flag' => 'SD', 'name' => 'Sudan', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '249', 'country_iso_code_3' => 'SDN', 'country_iso_code_2' => 'SD', 'currency_name' => 'Sudanese pound', 'currency_symbol' => 'ج.س'],
            ['code' => '+597', 'flag' => 'SR', 'name' => 'Suriname', 'languages' => 'Dutch', 'language_code' => 'nl', 'country_code' => '597', 'country_iso_code_3' => 'SUR', 'country_iso_code_2' => 'SR', 'currency_name' => 'Surinamese dollar', 'currency_symbol' => 'SR$'],
            ['code' => '+268', 'flag' => 'SZ', 'name' => 'Swaziland', 'languages' => 'Swazi, English', 'language_code' => 'ss, en', 'country_code' => '268', 'country_iso_code_3' => 'SWZ', 'country_iso_code_2' => 'SZ', 'currency_name' => 'Lilangeni', 'currency_symbol' => 'E'],
            ['code' => '+46', 'flag' => 'SE', 'name' => 'Sweden', 'languages' => 'Swedish', 'language_code' => 'sv', 'country_code' => '46', 'country_iso_code_3' => 'SWE', 'country_iso_code_2' => 'SE', 'currency_name' => 'Swedish krona', 'currency_symbol' => 'kr'],
            ['code' => '+41', 'flag' => 'CH', 'name' => 'Switzerland', 'languages' => 'German, French, Italian, Romansh', 'language_code' => 'de, fr, it, rm', 'country_code' => '41', 'country_iso_code_3' => 'CHE', 'country_iso_code_2' => 'CH', 'currency_name' => 'Swiss franc', 'currency_symbol' => 'CHF'],
            ['code' => '+963', 'flag' => 'SY', 'name' => 'Syria', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '963', 'country_iso_code_3' => 'SYR', 'country_iso_code_2' => 'SY', 'currency_name' => 'Syrian pound', 'currency_symbol' => '£'],
            ['code' => '+886', 'flag' => 'TW', 'name' => 'Taiwan', 'languages' => 'Mandarin', 'language_code' => 'zh', 'country_code' => '886', 'country_iso_code_3' => 'TWN', 'country_iso_code_2' => 'TW', 'currency_name' => 'New Taiwan dollar', 'currency_symbol' => 'NT$'],
            ['code' => '+992', 'flag' => 'TJ', 'name' => 'Tajikistan', 'languages' => 'Tajik', 'language_code' => 'tg', 'country_code' => '992', 'country_iso_code_3' => 'TJK', 'country_iso_code_2' => 'TJ', 'currency_name' => 'Tajikistani somoni', 'currency_symbol' => 'SM'],
            ['code' => '+255', 'flag' => 'TZ', 'name' => 'Tanzania', 'languages' => 'Swahili, English', 'language_code' => 'sw, en', 'country_code' => '255', 'country_iso_code_3' => 'TZA', 'country_iso_code_2' => 'TZ', 'currency_name' => 'Tanzanian shilling', 'currency_symbol' => 'TSh'],
            ['code' => '+66', 'flag' => 'TH', 'name' => 'Thailand', 'languages' => 'Thai', 'language_code' => 'th', 'country_code' => '66', 'country_iso_code_3' => 'THA', 'country_iso_code_2' => 'TH', 'currency_name' => 'Thai baht', 'currency_symbol' => '฿'],
            ['code' => '+228', 'flag' => 'TG', 'name' => 'Togo', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '228', 'country_iso_code_3' => 'TGO', 'country_iso_code_2' => 'TG', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA'],
            ['code' => '+690', 'flag' => 'TK', 'name' => 'Tokelau', 'languages' => 'Tokelauan, English', 'language_code' => 'tk, en', 'country_code' => '690', 'country_iso_code_3' => 'TKL', 'country_iso_code_2' => 'TK', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$'],
            ['code' => '+676', 'flag' => 'TO', 'name' => 'Tonga', 'languages' => 'Tongan, English', 'language_code' => 'to, en', 'country_code' => '676', 'country_iso_code_3' => 'TON', 'country_iso_code_2' => 'TO', 'currency_name' => 'Tongan paʻanga', 'currency_symbol' => 'T$'],
            ['code' => '+1 868', 'flag' => 'TT', 'name' => 'Trinidad and Tobago', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1 868', 'country_iso_code_3' => 'TTO', 'country_iso_code_2' => 'TT', 'currency_name' => 'Trinidad and Tobago dollar', 'currency_symbol' => 'TT$'],
            ['code' => '+216', 'flag' => 'TN', 'name' => 'Tunisia', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '216', 'country_iso_code_3' => 'TUN', 'country_iso_code_2' => 'TN', 'currency_name' => 'Tunisian dinar', 'currency_symbol' => 'د.ت'],
            ['code' => '+90', 'flag' => 'TR', 'name' => 'Turkey', 'languages' => 'Turkish', 'language_code' => 'tr', 'country_code' => '90', 'country_iso_code_3' => 'TUR', 'country_iso_code_2' => 'TR', 'currency_name' => 'Turkish lira', 'currency_symbol' => '₺'],
            ['code' => '+993', 'flag' => 'TM', 'name' => 'Turkmenistan', 'languages' => 'Turkmen', 'language_code' => 'tk', 'country_code' => '993', 'country_iso_code_3' => 'TKM', 'country_iso_code_2' => 'TM', 'currency_name' => 'Turkmenistan manat', 'currency_symbol' => 'm'],
            ['code' => '+1 649', 'flag' => 'TC', 'name' => 'Turks and Caicos Islands', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1 649', 'country_iso_code_3' => 'TCA', 'country_iso_code_2' => 'TC', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['code' => '+688', 'flag' => 'TV', 'name' => 'Tuvalu', 'languages' => 'English, Tuvaluan', 'language_code' => 'en, tv', 'country_code' => '688', 'country_iso_code_3' => 'TUV', 'country_iso_code_2' => 'TV', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$'],
            ['code' => '+256', 'flag' => 'UG', 'name' => 'Uganda', 'languages' => 'English, Swahili', 'language_code' => 'en, sw', 'country_code' => '256', 'country_iso_code_3' => 'UGA', 'country_iso_code_2' => 'UG', 'currency_name' => 'Ugandan shilling', 'currency_symbol' => 'USh'],
            ['code' => '+380', 'flag' => 'UA', 'name' => 'Ukraine', 'languages' => 'Ukrainian', 'language_code' => 'uk', 'country_code' => '380', 'country_iso_code_3' => 'UKR', 'country_iso_code_2' => 'UA', 'currency_name' => 'Ukrainian hryvnia', 'currency_symbol' => '₴'],
            ['code' => '+971', 'flag' => 'AE', 'name' => 'United Arab Emirates', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '971', 'country_iso_code_3' => 'ARE', 'country_iso_code_2' => 'AE', 'currency_name' => 'United Arab Emirates dirham', 'currency_symbol' => 'د.إ'],
            ['code' => '+44', 'flag' => 'GB', 'name' => 'United Kingdom', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '44', 'country_iso_code_3' => 'GBR', 'country_iso_code_2' => 'GB', 'currency_name' => 'Pound sterling', 'currency_symbol' => '£'],
            ['code' => '+1', 'flag' => 'US', 'name' => 'United States', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '1', 'country_iso_code_3' => 'USA', 'country_iso_code_2' => 'US', 'currency_name' => 'United States dollar', 'currency_symbol' => '$'],
            ['code' => '+598', 'flag' => 'UY', 'name' => 'Uruguay', 'languages' => 'Spanish', 'language_code' => 'es', 'country_code' => '598', 'country_iso_code_3' => 'URY', 'country_iso_code_2' => 'UY', 'currency_name' => 'Uruguayan peso', 'currency_symbol' => '$'],
            ['code' => '+998', 'flag' => 'UZ', 'name' => 'Uzbekistan', 'languages' => 'Uzbek', 'language_code' => 'uz', 'country_code' => '998', 'country_iso_code_3' => 'UZB', 'country_iso_code_2' => 'UZ', 'currency_name' => 'Uzbekistani som', 'currency_symbol' => 'сўм'],
            ['code' => '+379', 'flag' => 'VA', 'name' => 'Vatican City', 'languages' => 'Italian, Latin', 'language_code' => 'it, la', 'country_code' => '379', 'country_iso_code_3' => 'VAT', 'country_iso_code_2' => 'VA', 'currency_name' => 'Euro', 'currency_symbol' => '€'],
            ['code' => '+58', 'flag' => 'VE', 'name' => 'Venezuela', 'languages' => 'Spanish', 'language_code' => 'es', 'country_code' => '58', 'country_iso_code_3' => 'VEN', 'country_iso_code_2' => 'VE', 'currency_name' => 'Venezuelan bolívar', 'currency_symbol' => 'Bs'],
            ['code' => '+84', 'flag' => 'VN', 'name' => 'Vietnam', 'languages' => 'Vietnamese', 'language_code' => 'vi', 'country_code' => '84', 'country_iso_code_3' => 'VNM', 'country_iso_code_2' => 'VN', 'currency_name' => 'Vietnamese đồng', 'currency_symbol' => '₫'],
            ['code' => '+681', 'flag' => 'WF', 'name' => 'Wallis and Futuna', 'languages' => 'French', 'language_code' => 'fr', 'country_code' => '681', 'country_iso_code_3' => 'WLF', 'country_iso_code_2' => 'WF', 'currency_name' => 'CFP franc', 'currency_symbol' => 'XPF'],
            ['code' => '+967', 'flag' => 'YE', 'name' => 'Yemen', 'languages' => 'Arabic', 'language_code' => 'ar', 'country_code' => '967', 'country_iso_code_3' => 'YEM', 'country_iso_code_2' => 'YE', 'currency_name' => 'Yemeni rial', 'currency_symbol' => '﷼'],
            ['code' => '+260', 'flag' => 'ZM', 'name' => 'Zambia', 'languages' => 'English', 'language_code' => 'en', 'country_code' => '260', 'country_iso_code_3' => 'ZMB', 'country_iso_code_2' => 'ZM', 'currency_name' => 'Zambian kwacha', 'currency_symbol' => 'ZK'],
            ['code' => '+263', 'flag' => 'ZW', 'name' => 'Zimbabwe', 'languages' => 'English, Shona, Ndebele', 'language_code' => 'en, sn, nd', 'country_code' => '263', 'country_iso_code_3' => 'ZWE', 'country_iso_code_2' => 'ZW', 'currency_name' => 'Zimbabwean dollar', 'currency_symbol' => 'Z$'],
        ];

        foreach ($countries as $data) 
        {
            $country = new Country();

            $country->name = $data['name'];
            $country->phone_code = $data['code'];
            $country->flag = $data['flag'];
            $country->languages = $data['languages'];
            $country->language_code = $data['language_code'];
            $country->country_code = $data['country_code'];
            $country->country_iso_code_2 = $data['country_iso_code_2'];
            $country->country_iso_code_3 = $data['country_iso_code_3'];
            $country->currency_name = $data['currency_name'];
            $country->currency_symbol = $data['currency_symbol'];
            $country->reference_id = Helper::getUUID('countries', 'reference_id'); 

            $country->save();
        }
    }
}
